demo:
    #!/usr/bin/env -S runrust --base-path {{justfile_directory()}}
    //! ```cargo
    //! [dependencies]
    //! dummy = { path = "./dummy" }
    //! ```
    fn main() {
       let result = dummy::add(1, 2);
       println!("result: {}", result);
    }

